#+STARTUP: overview
#+SEQ_TODO: TODO STARTED NEXT WAITING | DONE DEFERRED CANCEL
#+STARTUP: hidestars
#+STARTUP: logdone
#+STARTUP: lognotestats

* PDFtags

A program to organize many pdfs using hierarchical tags.

The main goal is to make it easy to tag many pdfs, search by tags, and
open selected pdfs.

Additional, the program (or separate helper scripts) should make it
easy to help manage the pdfs. For example, find duplicates, associate
original pdfs with annotated ones.

The program should also be able to extract DOI information, look up
metadata, and display the metadata and export to bibtex.


** Install

   git clone https://github.com/arunpersaud/pdftags.git

   'cd' into directory

   ./pdftags

   set the directory of your pdfs and pdf viewer in the init file (the
   program will point you to the right file)


** TO DO list
   - edit metadata, auto-complete from existing data
   - make everything easy to use with keyboard shortcuts
   - help and about entries in the menu
   - ask for path and viewer information during startup
   - create pdf version for annotation
   - currently using google scholar, but perhaps also use crossref
     https://www.crossref.org/labs/resolving-citations-we-dont-need-no-stinkin-parser/
   - don't overwrite hand edited metadata?
   - create backup of database periodically (perhaps daily and keep daily, weekly, and monthly versions?)
   - make thumbnails of pages and show those on the overview?
   - find duplicates by metadata and or md5, if same metadata, but not md5 link as version?
   - unlink versions of pdfs
   - check for new files (monitor thread?) <- already works somewhat, e.g. doesn't take too long at the moment during startup
   - use gtk.application and add command line interface this way

** Contribute

Pull requests and feedback welcome!
