"""added journal metadata

Revision ID: 39ba582aac62
Revises: b8e5023ef4a7
Create Date: 2018-02-11 17:46:08.944330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ba582aac62'
down_revision = 'b8e5023ef4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('institute', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdfpeople',
    sa.Column('pdf_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdfs.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], )
    )
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doi', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('journal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metadata_complete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pages', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('volume', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pdf_journal', 'journals', ['journal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pdf_journal', type_='foreignkey')
        batch_op.drop_column('year')
        batch_op.drop_column('volume')
        batch_op.drop_column('title')
        batch_op.drop_column('pages')
        batch_op.drop_column('number')
        batch_op.drop_column('metadata_complete')
        batch_op.drop_column('journal_id')
        batch_op.drop_column('doi')

    op.drop_table('pdfpeople')
    op.drop_table('people')
    op.drop_table('journals')
    # ### end Alembic commands ###
